**Quiz 1.**

Type in your Student ID and full name in the box below.

### Type in your student ID and Name here
ID 6581030520
Name Pakorn Sagulkoo

In [2]:
# Must run this statement first
!pip install --quiet mxnet

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.1/49.1 MB 13.7 MB/s eta 0:00:00


###1. Create tensors: $x_1$, $x_2$, $x_3$, $x_4$, $x_5$, $x_6$ and three constants $m$, $n$, and $k$ from following instructions.

1.1. $m = 3$, $n = 5$, $k = 4$

$x_1=\left[7\right]$, $x_2 = \left[1 \dots m\right]$, $x_3=\left[ \begin{array}{ccc} 3 & -2 & 0\\ 2 & 1 &1\end{array}\right]$,

 $x_4 = $ matrix of 1's which dimension $(n-m) \times n $, $x_5= \left[ \begin{array}{ccccc} 3 & -1 & 1 & -2 & 0\end{array}\right]$,

 $x_6= $ matrix of 1's which dimension equal to  $x_3 $.

In [18]:
from mxnet import nd
from mxnet import np

In [4]:
m=3; n=5; k=4

In [5]:
x1 = nd.array([7]); x1


[7.]
<NDArray 1 @cpu(0)>

In [6]:
x2 = nd.arange(0, m); x2


[0. 1. 2.]
<NDArray 3 @cpu(0)>

In [7]:
x3 = nd.array([[3, -2, 0], [2, 1, 1]]); x3


[[ 3. -2.  0.]
 [ 2.  1.  1.]]
<NDArray 2x3 @cpu(0)>

In [8]:
x4 = nd.ones((n-m, n)); x4


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
<NDArray 2x5 @cpu(0)>

In [9]:
x5 = nd.array([3, -1, 1, -2, 0]); x5


[ 3. -1.  1. -2.  0.]
<NDArray 5 @cpu(0)>

In [10]:
x6 = nd.ones_like(x3); x6


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

1.2. From 1.1, find the expression that would generate the following results. You are not allowed to type any constant in your expression. You do not need to use the index for any expression.

In [11]:
# 1.2.1. The expression to generate
#>> [[ 6. -4.  0.]
#    [ 4.  2.  2.]]
# is


In [12]:
x3 + x3


[[ 6. -4.  0.]
 [ 4.  2.  2.]]
<NDArray 2x3 @cpu(0)>

In [13]:
# 1.2.2. The expression to generate
#>> [[10.  5.  7.]
#    [ 9.  8.  8.]]
# is


In [14]:
x3 + x1


[[10.  5.  7.]
 [ 9.  8.  8.]]
<NDArray 2x3 @cpu(0)>

In [15]:
# 1.2.3. The expression to generate (Using .as_np_ndarray() to transform it to use with mx.np.matmul)
#>> array([[ 5.,  5.,  5.,  5.,  5.],
#          [-1., -1., -1., -1., -1.],
#          [ 1.,  1.,  1.,  1.,  1.]])
# is


In [19]:
cx3_np = x3.as_np_ndarray()
x4_np = x4.as_np_ndarray()
np.matmul(x3_np.T, x4_np)

array([[ 5.,  5.,  5.,  5.,  5.],
       [-1., -1., -1., -1., -1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [20]:
# 1.2.4. The expression to generate
#>> array([[[[ 0.],
#            [ 0.],
#            [ 0.],
#            [ 0.],
#            [ 0.]]],
#         [[[ 3.],
#           [-1.],
#           [ 1.],
#           [-2.],
#           [ 0.]]],
#         [[[ 6.],
#           [-2.],
#           [ 2.],
#           [-4.],
#           [ 0.]]]])
# is


In [21]:
x5_np = x5.as_np_ndarray()
x5_np = np.vstack(x5_np); x5_np

array([[ 3.],
       [-1.],
       [ 1.],
       [-2.],
       [ 0.]])

In [22]:
x2_np = x2.as_np_ndarray()
x2_np = np.vstack(x2_np); x2_np

array([[0.],
       [1.],
       [2.]])

In [23]:
x7 = np.matmul(x2_np, x5_np.T); x7

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 3., -1.,  1., -2.,  0.],
       [ 6., -2.,  2., -4.,  0.]])

In [24]:
x7.reshape(3,5,1)

array([[[ 0.],
        [ 0.],
        [ 0.],
        [ 0.],
        [ 0.]],

       [[ 3.],
        [-1.],
        [ 1.],
        [-2.],
        [ 0.]],

       [[ 6.],
        [-2.],
        [ 2.],
        [-4.],
        [ 0.]]])

In [25]:
# 1.2.5. The expression to generate
#>> [[  5.   2.]
#    [-10.  -1.]
#    [ -4.  -1.]]
# is

In [26]:
print(x2); print(x3); print(x6)


[0. 1. 2.]
<NDArray 3 @cpu(0)>

[[ 3. -2.  0.]
 [ 2.  1.  1.]]
<NDArray 2x3 @cpu(0)>

[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>


In [39]:
((x3 + x6 + x6) - x2*6).T


[[  5.   4.]
 [ -6.  -3.]
 [-10.  -9.]]
<NDArray 3x2 @cpu(0)>

In [40]:
# I cannot answer this question but in my idea I think array x2, x3, and x6 may participate in the operation to be desired matrix.