### Pakorn Sagulkoo 6581030520

### 1. Multiple Regression

Consider energy efficiency data  UCI repository which is supplied by Athanasios Tsanas and Angeliki Xifara. It contains 10 attributes :
1. X1 - Relative Compactness : continuous data with 0.62 to 0.98
2. X2 - Surface Area : continuous data with 514.50 to 808.50
3. X3 - Wall Area : continuous data with 245.00 to 416.50
4. X4 - Roof Area : continuous data with 110.25 to 220.50
5. X5 - Overall Height : continuous data with 3.50 to 7.00
6. X6 - Orientation : integer data with 2.00 to 5.00
7. X7 - Glazing Area : continuous data with 0.00 to 0.40
8. X8 - Glazing Area Distribution : integer data with 0.00 to 5.00
9. Y1 - Heating Load : continuous data with 6.01 to 43.10
10. Y2 - Cooling Load : continuous data with 10.90 to 48.03


The target is the $9^{th}$ attribute, the response variable Y1 and do not use Y2 in the model (but if you want to use, you can try).

There is no missing values.

You must implement the multiple regression using **SGD** from our class with average square loss.
- The total 10 points will give to a student who can find the parameters of this regression and achieve 0.01 for the average square loss.
- The total 7 points will give to a student who can find the parameters of this regression and achieve 0.1 for the average square loss.
- The total 5 points will give to a student who can make this code work with this dataset.

This data addresses in https://archive.ics.uci.edu/static/public/242/energy+efficiency.zip . Hint : you have to use !wget and !unzip this data from !wget and you can use pandas library and sklearn.preprocessing  to deal with data. TA's average square loss from last epoch is around 0.006. I think you can do better than me. Cheer up!! you can do this.


In [19]:
# Must run this statement first
!pip install --quiet mxnet

In [20]:
!wget https://archive.ics.uci.edu/static/public/242/energy+efficiency.zip

--2024-02-03 06:59:26--  https://archive.ics.uci.edu/static/public/242/energy+efficiency.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified
Saving to: ‘energy+efficiency.zip.1’

energy+efficiency.z     [  <=>               ]  74.53K   246KB/s    in 0.3s    

2024-02-03 06:59:28 (246 KB/s) - ‘energy+efficiency.zip.1’ saved [76321]



In [22]:
!unzip energy+efficiency.zip

Archive:  energy+efficiency.zip
replace ENB2012_data.xlsx? [y]es, [n]o, [A]ll, [N]one, [r]ename: 

In [65]:
# We will need to process this text dataset using pandas
# Deal with data in this block
import mxnet as mx
from mxnet import nd
import pandas as pd
import numpy as np

In [66]:
df = pd.read_excel("ENB2012_data.xlsx")
df

X1     X2     X3      X4   X5  X6   X7  X8     Y1     Y2
0    0.98  514.5  294.0  110.25  7.0   2  0.0   0  15.55  21.33
1    0.98  514.5  294.0  110.25  7.0   3  0.0   0  15.55  21.33
2    0.98  514.5  294.0  110.25  7.0   4  0.0   0  15.55  21.33
3    0.98  514.5  294.0  110.25  7.0   5  0.0   0  15.55  21.33
4    0.90  563.5  318.5  122.50  7.0   2  0.0   0  20.84  28.28
..    ...    ...    ...     ...  ...  ..  ...  ..    ...    ...
763  0.64  784.0  343.0  220.50  3.5   5  0.4   5  17.88  21.40
764  0.62  808.5  367.5  220.50  3.5   2  0.4   5  16.54  16.88
765  0.62  808.5  367.5  220.50  3.5   3  0.4   5  16.44  17.11
766  0.62  808.5  367.5  220.50  3.5   4  0.4   5  16.48  16.61
767  0.62  808.5  367.5  220.50  3.5   5  0.4   5  16.64  16.03

[768 rows x 10 columns]

In [202]:
# Contsruct a feature matrix by selecting column x1 to x8 and convert them to nd.array
features = df.iloc[:,:-2]
features = features.to_numpy()
features = nd.array(features)
features


[[9.800e-01 5.145e+02 2.940e+02 ... 2.000e+00 0.000e+00 0.000e+00]
 [9.800e-01 5.145e+02 2.940e+02 ... 3.000e+00 0.000e+00 0.000e+00]
 [9.800e-01 5.145e+02 2.940e+02 ... 4.000e+00 0.000e+00 0.000e+00]
 ...
 [6.200e-01 8.085e+02 3.675e+02 ... 3.000e+00 4.000e-01 5.000e+00]
 [6.200e-01 8.085e+02 3.675e+02 ... 4.000e+00 4.000e-01 5.000e+00]
 [6.200e-01 8.085e+02 3.675e+02 ... 5.000e+00 4.000e-01 5.000e+00]]
<NDArray 768x8 @cpu(0)>

In [203]:
# Contsruct a label vector by selecting column y1 and convert it to nd.array
labels = df.iloc[:,-2]
labels = labels.to_numpy()
labels = nd.array(labels)
labels


[15.55  15.55  15.55  15.55  20.84  21.46  20.71  19.68  19.5   19.95
 19.34  18.31  17.05  17.41  16.95  15.98  28.52  29.9   29.63  28.75
 24.77  23.93  24.77  23.93   6.07   6.05   6.01   6.04   6.37   6.4
  6.366  6.4    6.85   6.79   6.77   6.81   7.18   7.1    7.1    7.1
 10.85  10.54  10.77  10.56   8.6    8.49   8.45   8.5   24.58  24.63
 24.63  24.59  29.03  29.87  29.14  28.09  26.28  26.91  26.37  25.27
 23.53  24.03  23.54  22.58  35.56  37.12  36.9   35.94  32.96  32.12
 32.94  32.21  10.36  10.43  10.36  10.39  10.71  10.8   10.7   10.75
 11.11  11.13  11.09  11.16  11.68  11.69  11.7   11.69  15.41  15.2
 15.42  15.21  12.96  12.97  12.93  13.02  24.29  24.31  24.13  24.25
 28.88  29.68  28.83  27.9   26.48  27.02  26.33  25.36  23.75  24.23
 23.67  22.79  35.65  37.26  36.97  36.03  33.16  32.4   33.12  32.41
 10.42  10.46  10.32  10.45  10.64  10.72  10.55  10.68  11.45  11.46
 11.32  11.49  11.45  11.42  11.33  11.43  15.41  15.18  15.34  15.19
 12.88  13.    12.97  

In [204]:
# Build multiple regression from ground-up
import mxnet as mx
from mxnet import nd, autograd, gluon

In [205]:
# Import data
from mxnet.gluon import data as gdata

batch_size = 12
# Combine the features and labels of the training data
dataset = gdata.ArrayDataset(features, labels)
# Randomly reading mini-batches
data_iter = gdata.DataLoader(dataset, batch_size, shuffle=True)

# Read a batch to see how it works
for X, y in data_iter:
    print(X, y)
    break


[[7.6000e-01 6.6150e+02 4.1650e+02 1.2250e+02 7.0000e+00 3.0000e+00
  4.0000e-01 5.0000e+00]
 [7.9000e-01 6.3700e+02 3.4300e+02 1.4700e+02 7.0000e+00 3.0000e+00
  1.0000e-01 5.0000e+00]
 [9.0000e-01 5.6350e+02 3.1850e+02 1.2250e+02 7.0000e+00 2.0000e+00
  1.0000e-01 3.0000e+00]
 [6.6000e-01 7.5950e+02 3.1850e+02 2.2050e+02 3.5000e+00 4.0000e+00
  2.5000e-01 3.0000e+00]
 [6.4000e-01 7.8400e+02 3.4300e+02 2.2050e+02 3.5000e+00 5.0000e+00
  4.0000e-01 3.0000e+00]
 [8.2000e-01 6.1250e+02 3.1850e+02 1.4700e+02 7.0000e+00 3.0000e+00
  1.0000e-01 4.0000e+00]
 [6.2000e-01 8.0850e+02 3.6750e+02 2.2050e+02 3.5000e+00 3.0000e+00
  1.0000e-01 3.0000e+00]
 [7.1000e-01 7.1050e+02 2.6950e+02 2.2050e+02 3.5000e+00 2.0000e+00
  4.0000e-01 1.0000e+00]
 [9.8000e-01 5.1450e+02 2.9400e+02 1.1025e+02 7.0000e+00 5.0000e+00
  4.0000e-01 3.0000e+00]
 [6.9000e-01 7.3500e+02 2.9400e+02 2.2050e+02 3.5000e+00 5.0000e+00
  2.5000e-01 3.0000e+00]
 [8.2000e-01 6.1250e+02 3.1850e+02 1.4700e+02 7.0000e+00 3.0000e+00
 

In [206]:
# Assign an initial model
from mxnet.gluon import nn
net = nn.Sequential()
net.add(nn.Dense(1))

# Assign initial parameters
from mxnet import init
net.initialize(init.Normal(sigma=0.1))

# Assign a loss of function
from mxnet.gluon import loss as gloss
loss = gloss.L2Loss()  # The squared loss is also known as the L2 norm loss

# Assign an algorithm for optimization
from mxnet import gluon
trainer = gluon.Trainer(net.collect_params(), 'sgd', {'learning_rate': 0.000003})

In [207]:
# Learning process
num_epochs = 20
for epoch in range(1, num_epochs + 1):
    for X, y in data_iter:
        with autograd.record():
            l = loss(net(X), y)
        l.backward()
        trainer.step(batch_size)
    l = loss(net(features), labels)
    print('epoch %d, loss: %f' % (epoch, l.mean().asnumpy()))

epoch 1, loss: 84.491432
epoch 2, loss: 25.406479
epoch 3, loss: 27.924395
epoch 4, loss: 43.708065
epoch 5, loss: 20.238197
epoch 6, loss: 17.991774
epoch 7, loss: 18.369684
epoch 8, loss: 77.540398
epoch 9, loss: 91.395561
epoch 10, loss: 19.326824
epoch 11, loss: 53.022411
epoch 12, loss: 22.514631
epoch 13, loss: 39.095646
epoch 14, loss: 19.185499
epoch 15, loss: 32.205952
epoch 16, loss: 32.927124
epoch 17, loss: 60.703259
epoch 18, loss: 30.921782
epoch 19, loss: 17.966661
epoch 20, loss: 27.520510


In [208]:
w = net[0].weight.data()
b = net[0].bias.data()
print(w, b)


[[-0.00398428 -0.02596942  0.15291291 -0.08100829 -0.00722696  0.13742603
   0.09210149  0.0494801 ]]
<NDArray 1x8 @cpu(0)> 
[0.00161601]
<NDArray 1 @cpu(0)>
